name: Check yaid-js

on:
  pull_request:
    branches: [main]
    paths:
      - yaid-js/**

jobs:
  check-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1

      - name: Install dependecies
        working-directory: ./yaid-js
        run: bun install

      - name: Lint
        working-directory: ./yaid-js
        run: bun run lint

      - name: Test js
        working-directory: ./yaid-js
        run: bun run test

      - name: Build
        working-directory: ./yaid-js
        run: bun run build
