on:
    release:
        types: [created]

jobs:
    releases-go:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos: [linux, windows, darwin]
                goarch: [amd64, arm64]
        steps:
            - uses: actions/checkout@v3

            - name: Build website
              run: npm run build
              working-directory: ./site

            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./site/dist
