name: Release Please yaid-py

on:
  push:
    branches: [main]
    paths:
      - yaid-py/**

permissions:
  contents: write
  pull-requests: write

jobs:
  release-py:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: yaid-py
          monorepo-tags: true
